"""
Master data initialization
"""

from .sap_master import (
    SAP_TAX_CODE_MASTER,
    SAP_TAX_CODE_DESCRIPTIONS,
    UNION_TERRITORIES as SAP_UNION_TERRITORIES
)
from .oracle_master import (
    ORACLE_TAX_CODE_MASTER,
    ORACLE_TAX_CODE_DESCRIPTIONS,
    UNION_TERRITORIES as ORACLE_UNION_TERRITORIES
)
from .ms360_master import (
    MS360_TAX_CODE_MASTER,
    MS360_TAX_CODE_DESCRIPTIONS,
    UNION_TERRITORIES as MS360_UNION_TERRITORIES
)

__all__ = [
    'SAP_TAX_CODE_MASTER',
    'SAP_TAX_CODE_DESCRIPTIONS',
    'SAP_UNION_TERRITORIES',
    'ORACLE_TAX_CODE_MASTER',
    'ORACLE_TAX_CODE_DESCRIPTIONS',
    'ORACLE_UNION_TERRITORIES',
    'MS360_TAX_CODE_MASTER',
    'MS360_TAX_CODE_DESCRIPTIONS',
    'MS360_UNION_TERRITORIES',
]
